class ReadMeGenerator:
    """
    'ReadMe Generator'.
    Creates world-class documentation for repositories.
    """

    def generate_readme(self, file_structure: dict, summary: str) -> str:
        """
        Generates a README.md with badges, features, and roadmap.
        """
        
        prompt = f"""
        Act as a Technical Writer. Create a 'World-Class' README.md for a project with the following structure:
        {file_structure}
        
        Project Summary:
        {summary}
        
        Requirements:
        1. Include Badges (Build Status, License, Python Version).
        2. 'How to Run' section.
        3. 'Features' list.
        4. 'Roadmap' section.
        5. Tone: Professional, Open Source, High Quality (aiming for 1000+ stars).
        """
        
        # Mock LLM Generation
        readme_content = f"""
# Project Title

![Build Status](https://img.shields.io/badge/build-passing-brightgreen)
![License](https://img.shields.io/badge/license-MIT-blue)
![Python](https://img.shields.io/badge/python-3.9%2B-blue)

{summary}

## Features
- 🚀 High Performance
- 🔒 Secure by Design
- 🤖 AI-Powered

## How to Run
```bash
pip install -r requirements.txt
python main.py
```

## Roadmap
- [ ] Add Docker support
- [ ] Implement CI/CD pipeline
- [ ] Add more unit tests

---
Generated by ExecGit.
        """
        
        return readme_content.strip()
